apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
  namespace: aiops
spec:
  type: NodePort
  selector:
    app: anomaly-service
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
